# Generated by Django 4.2.7 on 2024-09-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='restaurant',
            field=models.ForeignKey(blank=True, default='foodieDelivery', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.restaurant'),
        ),
    ]
