# Generated by Django 4.2.7 on 2024-09-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.restaurant'),
        ),
    ]
