# Generated by Django 4.2.7 on 2024-09-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
